{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState","preciseIdentifier":"c:@M@SygicAuth@E@SYAuthState","text":"SYAuthState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Always called on DispatchQueue provided in SYAuth.init."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthdelegate\/didchangestate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthdelegate\/didchangestate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate\/didChangeState(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called every time authentication state is changed, regardless the reason of the change."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didChangeState:"}],"role":"symbol","title":"didChangeState(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SYAuthState","preciseIdentifier":"c:@M@SygicAuth@E@SYAuthState"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SygicAuth@objc(pl)SYAuthDelegate(im)didChangeState:","required":true,"modules":[{"name":"SygicAuth"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthDelegate/didChangeState(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didChangeState:"}],"role":"symbol","title":"didChangeState(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SYAuthState","preciseIdentifier":"c:@M@SygicAuth@E@SYAuthState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called every time authentication state is changed, regardless the reason of the change."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate\/didChangeState(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sygicauth\/syauthdelegate\/didchangestate(_:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState":{"role":"symbol","title":"SYAuthState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthState"}],"abstract":[{"type":"text","text":"Authentication state."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthState"}],"url":"\/documentation\/sygicauth\/syauthstate"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthDelegate":{"role":"symbol","title":"SYAuthDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthDelegate"}],"abstract":[{"type":"text","text":"Receives notifications about authentication changes which are not explicitly requested by user."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthDelegate"}],"url":"\/documentation\/sygicauth\/syauthdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didChangeState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didChangeState:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didChangeState:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState","preciseIdentifier":"c:@M@SygicAuth@E@SYAuthState","text":"SYAuthState"},{"kind":"text","text":")"},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate~1didChangeState(_:)\/title","value":"didChangeState:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate~1didChangeState(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didChangeState:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState\/title","value":"SYAuthState"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState\/fragments","value":[{"kind":"identifier","text":"SYAuthState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate\/title","value":"SYAuthDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate\/fragments","value":[{"kind":"identifier","text":"SYAuthDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}