{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSignOutWithoutRequest"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Always called on DispatchQueue provided in SYAuth.init."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Called when:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"access token and refresh token expired, need to provide sign in data again;"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"stored authentication is connected to an account and cannot be used,"},{"type":"text","text":" "},{"type":"text","text":"because the current config doesn’t match the stored config"},{"type":"text","text":" "},{"type":"text","text":"(called after initialization, but not earlier than the delegate is set)."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthdelegate\/didsignoutwithoutrequest()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthdelegate\/didsignoutwithoutrequest()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate\/didSignOutWithoutRequest()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Means authentication was connected to an account (of any type), and became not connected to an account anymore."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didSignOutWithoutRequest"}],"role":"symbol","title":"didSignOutWithoutRequest()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSignOutWithoutRequest"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@SygicAuth@objc(pl)SYAuthDelegate(im)didSignOutWithoutRequest","required":true,"modules":[{"name":"SygicAuth"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthDelegate/didSignOutWithoutRequest()":{"navigatorTitle":[{"kind":"identifier","text":"didSignOutWithoutRequest"}],"role":"symbol","title":"didSignOutWithoutRequest()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSignOutWithoutRequest"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Means authentication was connected to an account (of any type), and became not connected to an account anymore."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate\/didSignOutWithoutRequest()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sygicauth\/syauthdelegate\/didsignoutwithoutrequest()"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthDelegate":{"role":"symbol","title":"SYAuthDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthDelegate"}],"abstract":[{"type":"text","text":"Receives notifications about authentication changes which are not explicitly requested by user."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthDelegate"}],"url":"\/documentation\/sygicauth\/syauthdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didSignOutWithoutRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSignOutWithoutRequest"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didSignOutWithoutRequest"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate~1didSignOutWithoutRequest()\/title","value":"didSignOutWithoutRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate~1didSignOutWithoutRequest()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSignOutWithoutRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate\/title","value":"SYAuthDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate\/fragments","value":[{"kind":"identifier","text":"SYAuthDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}