{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHeaders"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthBuildHeadersCompletion","preciseIdentifier":"s:9SygicAuth28SYAuthBuildHeadersCompletiona","text":"SYAuthBuildHeadersCompletion"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Called asynchronously on DispatchQueue provided in SYAuth.init."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It is expected that an application calls "},{"type":"codeVoice","code":"buildHeaders"},{"type":"text","text":" for each request to Sygic online services,"},{"type":"text","text":" "},{"type":"text","text":"the method is optimized for this purpose."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Thread-safe."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Typically the headers are prepared quickly based on the cached access token,"},{"type":"text","text":" "},{"type":"text","text":"but if the token expired or doesn’t exist (e.g. after signOut or requestAuthenticationRefresh),"},{"type":"text","text":" "},{"type":"text","text":"SYAuth will make a network request to obtain the new access token."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If not authenticated, will try to authenticate without account using SYAuthConfig.deviceCode."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If authentication expired, will try to refresh it."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"May call delegate.didSignOutWithoutRequest (asynchronously on DispatchQueue provided in SYAuth.init)."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauth\/buildheaders(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauth\/buildheaders(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/buildHeaders(completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Prepares authentication headers based on the currently authenticated user identity."},{"type":"text","text":" "},{"type":"text","text":"Authentication headers are to be added to every NSURLRequest sent to Sygic online services."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHeaders"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthBuildHeadersCompletion","preciseIdentifier":"s:9SygicAuth28SYAuthBuildHeadersCompletiona"},{"kind":"text","text":")"}],"title":"buildHeaders(completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SygicAuth@objc(cs)SYAuth(im)buildHeadersWithCompletion:","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"buildHeadersWithCompletion:"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/buildHeaders(completion:)":{"role":"symbol","title":"buildHeaders(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHeaders"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthBuildHeadersCompletion","preciseIdentifier":"s:9SygicAuth28SYAuthBuildHeadersCompletiona"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Prepares authentication headers based on the currently authenticated user identity."},{"type":"text","text":" "},{"type":"text","text":"Authentication headers are to be added to every NSURLRequest sent to Sygic online services."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/buildHeaders(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHeadersWithCompletion:"}],"url":"\/documentation\/sygicauth\/syauth\/buildheaders(completion:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth":{"role":"symbol","title":"SYAuth","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuth"}],"abstract":[{"type":"text","text":"Provides authentication for Sygic online services."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuth"}],"url":"\/documentation\/sygicauth\/syauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthBuildHeadersCompletion":{"role":"symbol","title":"SYAuthBuildHeadersCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthBuildHeadersCompletion"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthBuildHeadersCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthBuildHeadersCompletion"}],"url":"\/documentation\/sygicauth\/syauthbuildheaderscompletion"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"buildHeadersWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"buildHeadersWithCompletion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"buildHeadersWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum SYAuthOperationResult, NSDictionary<NSString *,NSString *> *, NSError *)","preciseIdentifier":"c:BFv(#$@M@SygicAuth@E@SYAuthOperationResult#*Q$objc(cs)NSDictionary#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1buildHeaders(completion:)\/title","value":"buildHeadersWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1buildHeaders(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"buildHeadersWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/title","value":"SYAuth"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/fragments","value":[{"kind":"identifier","text":"SYAuth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}