{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig","preciseIdentifier":"c:@M@SygicAuth@objc(cs)SYAuthConfig","text":"SYAuthConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"network"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthNetworkProvider","text":"SYAuthNetworkProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"storage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthStorageProvider","text":"SYAuthStorageProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthDelegate","text":"SYAuthDelegate"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Combination of user-independent parameters"},{"type":"text","text":" "},{"type":"text","text":"which remain constant for the application installed on a specific device."}]}]},{"name":"network","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Network provider, responsible for asynchronous sending network requests"},{"type":"text","text":" "},{"type":"text","text":"and delivering responses from server."}]}]},{"name":"storage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Storage provider, responsible for saving authentication data"},{"type":"text","text":" "},{"type":"text","text":"to make it available again after application restart."}]}]},{"name":"queue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Asynchronous completions and delegate methods will be called on this DispatchQueue."},{"type":"text","text":" "},{"type":"text","text":"Can be serial or concurrent. If nil, DispatchQueue.global will be used."}]}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Delegate is notified about authentication changes which are not explicitly requested by user."},{"type":"text","text":" "},{"type":"text","text":"Delegate is optional and can be set later."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Storage provider instance must be dedicated to only one SYAuth instance."}]}],"type":"aside","name":"Precondition"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauth\/init(config:network:storage:queue:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauth\/init(config:network:storage:queue:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/init(config:network:storage:queue:delegate:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthConfig","preciseIdentifier":"c:@M@SygicAuth@objc(cs)SYAuthConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"network"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthNetworkProvider","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthNetworkProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"storage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthStorageProvider","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthStorageProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthDelegate","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthDelegate"},{"kind":"text","text":"?)"}],"title":"init(config:network:storage:queue:delegate:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SygicAuth@objc(cs)SYAuth(im)initWithConfig:network:storage:queue:delegate:","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfig:network:storage:queue:delegate:"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthStorageProvider":{"role":"symbol","title":"SYAuthStorageProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthStorageProvider"}],"abstract":[{"type":"text","text":"Provides persistent storage of String values accessed by String keys."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthStorageProvider"}],"url":"\/documentation\/sygicauth\/syauthstorageprovider"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthNetworkProvider":{"role":"symbol","title":"SYAuthNetworkProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthNetworkProvider"}],"abstract":[{"type":"text","text":"Provides network transport by asynchronous sending network requests."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthNetworkProvider"}],"url":"\/documentation\/sygicauth\/syauthnetworkprovider"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/init(config:network:storage:queue:delegate:)":{"role":"symbol","title":"init(config:network:storage:queue:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthConfig","preciseIdentifier":"c:@M@SygicAuth@objc(cs)SYAuthConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"network"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthNetworkProvider","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthNetworkProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"storage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthStorageProvider","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthStorageProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthDelegate","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthDelegate"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/init(config:network:storage:queue:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfig:network:storage:queue:delegate:"}],"url":"\/documentation\/sygicauth\/syauth\/init(config:network:storage:queue:delegate:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth":{"role":"symbol","title":"SYAuth","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuth"}],"abstract":[{"type":"text","text":"Provides authentication for Sygic online services."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuth"}],"url":"\/documentation\/sygicauth\/syauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig":{"role":"symbol","title":"SYAuthConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthConfig"}],"abstract":[{"type":"text","text":"Authentication parameters which are user-independent, and remain constant for an application installed on a specific device."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthConfig"}],"url":"\/documentation\/sygicauth\/syauthconfig"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthDelegate":{"role":"symbol","title":"SYAuthDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthDelegate"}],"abstract":[{"type":"text","text":"Receives notifications about authentication changes which are not explicitly requested by user."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthDelegate"}],"url":"\/documentation\/sygicauth\/syauthdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfig:network:storage:queue:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfig:network:storage:queue:delegate:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig","preciseIdentifier":"c:@M@SygicAuth@objc(cs)SYAuthConfig","text":"SYAuthConfig"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"config"},{"kind":"text","text":" "},{"kind":"identifier","text":"network:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SYAuthNetworkProvider>","preciseIdentifier":"c:Qo@M@SygicAuth@objc(pl)SYAuthNetworkProvider"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"network"},{"kind":"text","text":" "},{"kind":"identifier","text":"storage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SYAuthStorageProvider>","preciseIdentifier":"c:Qo@M@SygicAuth@objc(pl)SYAuthStorageProvider"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"storage"},{"kind":"text","text":" "},{"kind":"identifier","text":"queue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject<OS_dispatch_queue>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"queue"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SYAuthDelegate>","preciseIdentifier":"c:Qo@M@SygicAuth@objc(pl)SYAuthDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthStorageProvider\/title","value":"SYAuthStorageProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthStorageProvider\/fragments","value":[{"kind":"identifier","text":"SYAuthStorageProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider\/title","value":"SYAuthNetworkProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider\/fragments","value":[{"kind":"identifier","text":"SYAuthNetworkProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1init(config:network:storage:queue:delegate:)\/title","value":"initWithConfig:network:storage:queue:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1init(config:network:storage:queue:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfig:network:storage:queue:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/title","value":"SYAuth"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/fragments","value":[{"kind":"identifier","text":"SYAuth"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig\/title","value":"SYAuthConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig\/fragments","value":[{"kind":"identifier","text":"SYAuthConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate\/title","value":"SYAuthDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate\/fragments","value":[{"kind":"identifier","text":"SYAuthDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}