{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyAuthenticationRejected"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Thread-safe."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauth\/notifyauthenticationrejected()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauth\/notifyauthenticationrejected()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/notifyAuthenticationRejected()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Lets SygicAuth know, that one of Sygic services has rejected the authentication of the current user identity."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyAuthenticationRejected"},{"kind":"text","text":"()"}],"title":"notifyAuthenticationRejected()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SygicAuth@objc(cs)SYAuth(im)notifyAuthenticationRejected","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"notifyAuthenticationRejected"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth":{"role":"symbol","title":"SYAuth","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuth"}],"abstract":[{"type":"text","text":"Provides authentication for Sygic online services."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuth"}],"url":"\/documentation\/sygicauth\/syauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/notifyAuthenticationRejected()":{"role":"symbol","title":"notifyAuthenticationRejected()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyAuthenticationRejected"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Lets SygicAuth know, that one of Sygic services has rejected the authentication of the current user identity."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/notifyAuthenticationRejected()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifyAuthenticationRejected"}],"url":"\/documentation\/sygicauth\/syauth\/notifyauthenticationrejected()"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"notifyAuthenticationRejected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"notifyAuthenticationRejected"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"notifyAuthenticationRejected"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/title","value":"SYAuth"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/fragments","value":[{"kind":"identifier","text":"SYAuth"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1notifyAuthenticationRejected()\/title","value":"notifyAuthenticationRejected"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1notifyAuthenticationRejected()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"notifyAuthenticationRejected"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}