{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAuthenticationRefresh"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"buildHeaders"},{"type":"text","text":" can be called immediately (or any time later) after "},{"type":"codeVoice","code":"requestAuthenticationRefresh"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"codeVoice","code":"buildHeaders"},{"type":"text","text":" will complete the refresh and return headers based on the new token."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Thread-safe."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauth\/requestauthenticationrefresh()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauth\/requestauthenticationrefresh()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/requestAuthenticationRefresh()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Refresh the access token for the currently authenticated user identity."},{"type":"text","text":" "},{"type":"text","text":"This could be necessary for some online services to apply license changes (e.g. after purchase of some features)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAuthenticationRefresh"},{"kind":"text","text":"()"}],"title":"requestAuthenticationRefresh()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SygicAuth@objc(cs)SYAuth(im)requestAuthenticationRefresh","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"requestAuthenticationRefresh"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/requestAuthenticationRefresh()":{"role":"symbol","title":"requestAuthenticationRefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAuthenticationRefresh"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Refresh the access token for the currently authenticated user identity."},{"type":"text","text":" "},{"type":"text","text":"This could be necessary for some online services to apply license changes (e.g. after purchase of some features)."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/requestAuthenticationRefresh()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestAuthenticationRefresh"}],"url":"\/documentation\/sygicauth\/syauth\/requestauthenticationrefresh()"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth":{"role":"symbol","title":"SYAuth","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuth"}],"abstract":[{"type":"text","text":"Provides authentication for Sygic online services."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuth"}],"url":"\/documentation\/sygicauth\/syauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"requestAuthenticationRefresh"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestAuthenticationRefresh"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestAuthenticationRefresh"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1requestAuthenticationRefresh()\/title","value":"requestAuthenticationRefresh"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1requestAuthenticationRefresh()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestAuthenticationRefresh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/title","value":"SYAuth"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/fragments","value":[{"kind":"identifier","text":"SYAuth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}