{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signIn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentity"},{"kind":"text","text":" "},{"kind":"internalParam","text":"identity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity","preciseIdentifier":"c:@M@SygicAuth@objc(cs)SYAuthIdentity","text":"SYAuthIdentity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthSignInCompletion","preciseIdentifier":"s:9SygicAuth22SYAuthSignInCompletiona","text":"SYAuthSignInCompletion"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"identity","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User identity (account) to sign in with."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Called asynchronously on DispatchQueue provided in SYAuth.init."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Any data from SYAuthIdentity object is not saved."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Thread-safe."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauth\/signin(withidentity:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauth\/signin(withidentity:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/signIn(withIdentity:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authenticates with the user identity represented by SYAuthIdentity."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signIn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthIdentity","preciseIdentifier":"c:@M@SygicAuth@objc(cs)SYAuthIdentity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthSignInCompletion","preciseIdentifier":"s:9SygicAuth22SYAuthSignInCompletiona"},{"kind":"text","text":")"}],"title":"signIn(withIdentity:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SygicAuth@objc(cs)SYAuth(im)signInWithIdentity:completion:","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"signInWithIdentity:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthIdentity":{"role":"symbol","title":"SYAuthIdentity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthIdentity"}],"abstract":[{"type":"text","text":"User authentication identity (account)."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthIdentity"}],"url":"\/documentation\/sygicauth\/syauthidentity"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthSignInCompletion":{"role":"symbol","title":"SYAuthSignInCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthSignInCompletion"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthSignInCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthSignInCompletion"}],"url":"\/documentation\/sygicauth\/syauthsignincompletion"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/signIn(withIdentity:completion:)":{"role":"symbol","title":"signIn(withIdentity:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signIn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthIdentity","preciseIdentifier":"c:@M@SygicAuth@objc(cs)SYAuthIdentity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthSignInCompletion","preciseIdentifier":"s:9SygicAuth22SYAuthSignInCompletiona"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Authenticates with the user identity represented by SYAuthIdentity."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/signIn(withIdentity:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signInWithIdentity:completion:"}],"url":"\/documentation\/sygicauth\/syauth\/signin(withidentity:completion:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth":{"role":"symbol","title":"SYAuth","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuth"}],"abstract":[{"type":"text","text":"Provides authentication for Sygic online services."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuth"}],"url":"\/documentation\/sygicauth\/syauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"signInWithIdentity:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signInWithIdentity:completion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"signInWithIdentity:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity","preciseIdentifier":"c:@M@SygicAuth@objc(cs)SYAuthIdentity","text":"SYAuthIdentity"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"identity"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum SYAuthOperationResult, NSError *)","preciseIdentifier":"c:BFv(#$@M@SygicAuth@E@SYAuthOperationResult#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity\/title","value":"SYAuthIdentity"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity\/fragments","value":[{"kind":"identifier","text":"SYAuthIdentity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1signIn(withIdentity:completion:)\/title","value":"signInWithIdentity:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1signIn(withIdentity:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signInWithIdentity:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/title","value":"SYAuth"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/fragments","value":[{"kind":"identifier","text":"SYAuth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}