{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sygic.SygicAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sygic.SygicAuth\/objc(pl)NSObject","doc:\/\/com.sygic.SygicAuth\/s7CVarArgP","doc:\/\/com.sygic.SygicAuth\/s28CustomDebugStringConvertibleP","doc:\/\/com.sygic.SygicAuth\/s23CustomStringConvertibleP","doc:\/\/com.sygic.SygicAuth\/SQ","doc:\/\/com.sygic.SygicAuth\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authentication parameters which are user-independent, and remain constant for an application installed on a specific device."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthConfig"}],"title":"SYAuthConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SygicAuth@objc(cs)SYAuthConfig","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthConfig"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/init(url:appId:clientId:clientSecret:deviceCode:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/appId","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/clientId","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/clientSecret","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/deviceCode","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/url"]}],"references":{"doc://com.sygic.SygicAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sygic.SygicAuth\/SQ"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig/init(url:appId:clientId:clientSecret:deviceCode:)":{"role":"symbol","title":"init(url:appId:clientId:clientSecret:deviceCode:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deviceCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/init(url:appId:clientId:clientSecret:deviceCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUrl:appId:clientId:clientSecret:deviceCode:"}],"url":"\/documentation\/sygicauth\/syauthconfig\/init(url:appid:clientid:clientsecret:devicecode:)"},"doc://com.sygic.SygicAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sygic.SygicAuth\/SH"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig":{"role":"symbol","title":"SYAuthConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthConfig"}],"abstract":[{"type":"text","text":"Authentication parameters which are user-independent, and remain constant for an application installed on a specific device."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthConfig"}],"url":"\/documentation\/sygicauth\/syauthconfig"},"doc://com.sygic.SygicAuth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sygic.SygicAuth\/s23CustomStringConvertibleP"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig/clientSecret":{"role":"symbol","title":"clientSecret","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Client Secret specified during initialization."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/clientSecret","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientSecret"}],"url":"\/documentation\/sygicauth\/syauthconfig\/clientsecret"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[{"type":"text","text":"Authentication server URL specified during initialization."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/url","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"url"}],"url":"\/documentation\/sygicauth\/syauthconfig\/url"},"doc://com.sygic.SygicAuth/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sygic.SygicAuth\/objc(cs)NSObject"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig/appId":{"role":"symbol","title":"appId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Application ID specified during initialization."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/appId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appId"}],"url":"\/documentation\/sygicauth\/syauthconfig\/appid"},"doc://com.sygic.SygicAuth/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sygic.SygicAuth\/s7CVarArgP"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig/clientId":{"role":"symbol","title":"clientId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Client ID specified during initialization."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/clientId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientId"}],"url":"\/documentation\/sygicauth\/syauthconfig\/clientid"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig/deviceCode":{"role":"symbol","title":"deviceCode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Device identifier specified during initialization."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/deviceCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deviceCode"}],"url":"\/documentation\/sygicauth\/syauthconfig\/devicecode"},"doc://com.sygic.SygicAuth/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sygic.SygicAuth\/objc(pl)NSObject"},"doc://com.sygic.SygicAuth/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sygic.SygicAuth\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SYAuthConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/appId","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/clientId","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/clientSecret","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/deviceCode","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/url"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/init(url:appId:clientId:clientSecret:deviceCode:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1init(url:appId:clientId:clientSecret:deviceCode:)\/title","value":"initWithUrl:appId:clientId:clientSecret:deviceCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1init(url:appId:clientId:clientSecret:deviceCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUrl:appId:clientId:clientSecret:deviceCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig\/title","value":"SYAuthConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig\/fragments","value":[{"kind":"identifier","text":"SYAuthConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1clientSecret\/title","value":"clientSecret"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1clientSecret\/fragments","value":[{"kind":"identifier","text":"clientSecret"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1url\/title","value":"url"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1url\/fragments","value":[{"kind":"identifier","text":"url"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1appId\/title","value":"appId"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1appId\/fragments","value":[{"kind":"identifier","text":"appId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1clientId\/title","value":"clientId"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1clientId\/fragments","value":[{"kind":"identifier","text":"clientId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1deviceCode\/title","value":"deviceCode"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1deviceCode\/fragments","value":[{"kind":"identifier","text":"deviceCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}