{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthNetworkProvider"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Thread-safety is not required, if each NetworkProvider instance is dedicated to only one SYAuth instance."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthnetworkprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthnetworkprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides network transport by asynchronous sending network requests."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthNetworkProvider"}],"title":"SYAuthNetworkProvider","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SygicAuth@objc(pl)SYAuthNetworkProvider","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthNetworkProvider"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider\/sendRequest(_:completion:)"]}],"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthNetworkProvider/sendRequest(_:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"sendRequest:completion:"}],"role":"symbol","title":"sendRequest(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthSendRequestCompletion","preciseIdentifier":"s:9SygicAuth27SYAuthSendRequestCompletiona"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sends the request and calls the completion asynchronously."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider\/sendRequest(_:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sygicauth\/syauthnetworkprovider\/sendrequest(_:completion:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthNetworkProvider":{"role":"symbol","title":"SYAuthNetworkProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthNetworkProvider"}],"abstract":[{"type":"text","text":"Provides network transport by asynchronous sending network requests."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthNetworkProvider"}],"url":"\/documentation\/sygicauth\/syauthnetworkprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthNetworkProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthNetworkProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SYAuthNetworkProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider\/sendRequest(_:completion:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthNetworkProvider"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider~1sendRequest(_:completion:)\/title","value":"sendRequest:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider~1sendRequest(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendRequest:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider\/title","value":"SYAuthNetworkProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider\/fragments","value":[{"kind":"identifier","text":"SYAuthNetworkProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}