{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sygic.SygicAuth\/SQ","doc:\/\/com.sygic.SygicAuth\/SH","doc:\/\/com.sygic.SygicAuth\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authentication state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthState"}],"title":"SYAuthState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SygicAuth@E@SYAuthState","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthState"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/signedIn","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/signedOut"]},{"title":"Initializers","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/Equatable-Implementations","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState/signedIn":{"role":"symbol","title":"SYAuthState.signedIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"signedIn"}],"abstract":[{"type":"text","text":"Authentication is connected to an account (Sygic, Google, Facebook, Apple, or other)."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/signedIn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthStateSignedIn"}],"url":"\/documentation\/sygicauth\/syauthstate\/signedin"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState/signedOut":{"role":"symbol","title":"SYAuthState.signedOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"signedOut"}],"abstract":[{"type":"text","text":"Authentication is not connected to an account, user identity is represented by SYAuthConfig.deviceCode."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/signedOut","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthStateSignedOut"}],"url":"\/documentation\/sygicauth\/syauthstate\/signedout"},"doc://com.sygic.SygicAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sygic.SygicAuth\/SH"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sygicauth\/syauthstate\/equatable-implementations"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState":{"role":"symbol","title":"SYAuthState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthState"}],"abstract":[{"type":"text","text":"Authentication state."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthState"}],"url":"\/documentation\/sygicauth\/syauthstate"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth\/syauthstate\/init(rawvalue:)"},"doc://com.sygic.SygicAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sygic.SygicAuth\/SQ"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sygicauth\/syauthstate\/rawrepresentable-implementations"},"doc://com.sygic.SygicAuth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sygic.SygicAuth\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SYAuthState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/signedIn","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/signedOut"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState~1signedIn\/title","value":"SYAuthStateSignedIn"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState~1signedIn\/fragments","value":[{"kind":"identifier","text":"SYAuthStateSignedIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState~1signedOut\/title","value":"SYAuthStateSignedOut"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState~1signedOut\/fragments","value":[{"kind":"identifier","text":"SYAuthStateSignedOut"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState\/title","value":"SYAuthState"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState\/fragments","value":[{"kind":"identifier","text":"SYAuthState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}