{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthIdentity"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthidentity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthidentity"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sygic.SygicAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sygic.SygicAuth\/objc(pl)NSObject","doc:\/\/com.sygic.SygicAuth\/s7CVarArgP","doc:\/\/com.sygic.SygicAuth\/s28CustomDebugStringConvertibleP","doc:\/\/com.sygic.SygicAuth\/s23CustomStringConvertibleP","doc:\/\/com.sygic.SygicAuth\/SQ","doc:\/\/com.sygic.SygicAuth\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"User authentication identity (account)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthIdentity"}],"title":"SYAuthIdentity","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SygicAuth@objc(cs)SYAuthIdentity","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthIdentity"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(appleToken:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(appleToken:name:email:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(facebookToken:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(googleAuthCode:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(googleToken:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(userName:password:)"]}],"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthIdentity":{"role":"symbol","title":"SYAuthIdentity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthIdentity"}],"abstract":[{"type":"text","text":"User authentication identity (account)."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthIdentity"}],"url":"\/documentation\/sygicauth\/syauthidentity"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthIdentity/init(userName:password:)":{"role":"symbol","title":"init(userName:password:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(userName:password:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUserName:password:"}],"url":"\/documentation\/sygicauth\/syauthidentity\/init(username:password:)"},"doc://com.sygic.SygicAuth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sygic.SygicAuth\/s23CustomStringConvertibleP"},"doc://com.sygic.SygicAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sygic.SygicAuth\/SQ"},"doc://com.sygic.SygicAuth/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sygic.SygicAuth\/objc(cs)NSObject"},"doc://com.sygic.SygicAuth/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sygic.SygicAuth\/s28CustomDebugStringConvertibleP"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sygic.SygicAuth\/s7CVarArgP"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthIdentity/init(googleAuthCode:)":{"role":"symbol","title":"init(googleAuthCode:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"googleAuthCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(googleAuthCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithGoogleAuthCode:"}],"url":"\/documentation\/sygicauth\/syauthidentity\/init(googleauthcode:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthIdentity/init(googleToken:)":{"role":"symbol","title":"init(googleToken:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"googleToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(googleToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithGoogleToken:"}],"url":"\/documentation\/sygicauth\/syauthidentity\/init(googletoken:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthIdentity/init(facebookToken:)":{"role":"symbol","title":"init(facebookToken:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"facebookToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(facebookToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFacebookToken:"}],"url":"\/documentation\/sygicauth\/syauthidentity\/init(facebooktoken:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthIdentity/init(appleToken:name:email:)":{"role":"symbol","title":"init(appleToken:name:email:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appleToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(appleToken:name:email:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAppleToken:name:email:"}],"url":"\/documentation\/sygicauth\/syauthidentity\/init(appletoken:name:email:)"},"doc://com.sygic.SygicAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sygic.SygicAuth\/SH"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthIdentity/init(appleToken:)":{"role":"symbol","title":"init(appleToken:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appleToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(appleToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAppleToken:"}],"url":"\/documentation\/sygicauth\/syauthidentity\/init(appletoken:)"},"doc://com.sygic.SygicAuth/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sygic.SygicAuth\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthIdentity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthIdentity"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SYAuthIdentity"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(appleToken:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(appleToken:name:email:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(facebookToken:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(googleAuthCode:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(googleToken:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity\/init(userName:password:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthIdentity"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity\/title","value":"SYAuthIdentity"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity\/fragments","value":[{"kind":"identifier","text":"SYAuthIdentity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(userName:password:)\/title","value":"initWithUserName:password:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(userName:password:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUserName:password:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(googleAuthCode:)\/title","value":"initWithGoogleAuthCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(googleAuthCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGoogleAuthCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(googleToken:)\/title","value":"initWithGoogleToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(googleToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGoogleToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(facebookToken:)\/title","value":"initWithFacebookToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(facebookToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFacebookToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(appleToken:name:email:)\/title","value":"initWithAppleToken:name:email:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(appleToken:name:email:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAppleToken:name:email:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(appleToken:)\/title","value":"initWithAppleToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity~1init(appleToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAppleToken:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}