{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthOperationResult"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthoperationresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthoperationresult"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sygic.SygicAuth\/SQ","doc:\/\/com.sygic.SygicAuth\/SH","doc:\/\/com.sygic.SygicAuth\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Result of an authentication operation: signIn or buildHeaders."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthOperationResult"}],"title":"SYAuthOperationResult","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SygicAuth@E@SYAuthOperationResult","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResult"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/badResponseData","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/inconsistentResponse","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/networkError","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/notAuthenticated","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/serverError","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/success","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/tokenExpired","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/unrecognizedResponseCode","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/wrongCredentials"]},{"title":"Initializers","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/Equatable-Implementations","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/badResponseData":{"role":"symbol","title":"SYAuthOperationResult.badResponseData","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"badResponseData"}],"abstract":[{"type":"text","text":"Response data cannot be parsed as JSON or JSON doesn’t contain all the required fields."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/badResponseData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultBadResponseData"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/badresponsedata"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/tokenExpired":{"role":"symbol","title":"SYAuthOperationResult.tokenExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenExpired"}],"abstract":[{"type":"text","text":"Token used for sign in is expired."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/tokenExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultTokenExpired"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/tokenexpired"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/wrongCredentials":{"role":"symbol","title":"SYAuthOperationResult.wrongCredentials","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrongCredentials"}],"abstract":[{"type":"text","text":"User name or password is incorrect."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/wrongCredentials","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultWrongCredentials"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/wrongcredentials"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sygicauth\/syauthoperationresult\/equatable-implementations"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/networkError":{"role":"symbol","title":"SYAuthOperationResult.networkError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"abstract":[{"type":"text","text":"Sending network request completed with error."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/networkError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultNetworkError"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/networkerror"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/inconsistentResponse":{"role":"symbol","title":"SYAuthOperationResult.inconsistentResponse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inconsistentResponse"}],"abstract":[{"type":"text","text":"Network response is inconsistent, result is success but statusCode or data is nil."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/inconsistentResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultInconsistentResponse"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/inconsistentresponse"},"doc://com.sygic.SygicAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sygic.SygicAuth\/SQ"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth\/syauthoperationresult\/init(rawvalue:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/serverError":{"role":"symbol","title":"SYAuthOperationResult.serverError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}],"abstract":[{"type":"text","text":"Auth server responded with server error."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/serverError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultServerError"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/servererror"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/notAuthenticated":{"role":"symbol","title":"SYAuthOperationResult.notAuthenticated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthenticated"}],"abstract":[{"type":"text","text":"Auth server responded with a valid response, containing “not authenticated” result."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/notAuthenticated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultNotAuthenticated"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/notauthenticated"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/success":{"role":"symbol","title":"SYAuthOperationResult.success","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"abstract":[{"type":"text","text":"Requested operation completed successfully."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/success","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultSuccess"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/success"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sygicauth\/syauthoperationresult\/rawrepresentable-implementations"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult":{"role":"symbol","title":"SYAuthOperationResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthOperationResult"}],"abstract":[{"type":"text","text":"Result of an authentication operation: signIn or buildHeaders."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResult"}],"url":"\/documentation\/sygicauth\/syauthoperationresult"},"doc://com.sygic.SygicAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sygic.SygicAuth\/SH"},"doc://com.sygic.SygicAuth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sygic.SygicAuth\/SY"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/unrecognizedResponseCode":{"role":"symbol","title":"SYAuthOperationResult.unrecognizedResponseCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unrecognizedResponseCode"}],"abstract":[{"type":"text","text":"Auth server responded with unknown status code."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/unrecognizedResponseCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultUnrecognizedResponseCode"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/unrecognizedresponsecode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthOperationResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResult"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SYAuthOperationResult"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/badResponseData","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/inconsistentResponse","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/networkError","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/notAuthenticated","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/serverError","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/success","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/tokenExpired","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/unrecognizedResponseCode","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/wrongCredentials"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthOperationResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1badResponseData\/title","value":"SYAuthOperationResultBadResponseData"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1badResponseData\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultBadResponseData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1tokenExpired\/title","value":"SYAuthOperationResultTokenExpired"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1tokenExpired\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultTokenExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1wrongCredentials\/title","value":"SYAuthOperationResultWrongCredentials"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1wrongCredentials\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultWrongCredentials"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1networkError\/title","value":"SYAuthOperationResultNetworkError"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1networkError\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultNetworkError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1inconsistentResponse\/title","value":"SYAuthOperationResultInconsistentResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1inconsistentResponse\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultInconsistentResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1serverError\/title","value":"SYAuthOperationResultServerError"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1serverError\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultServerError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1notAuthenticated\/title","value":"SYAuthOperationResultNotAuthenticated"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1notAuthenticated\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultNotAuthenticated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1success\/title","value":"SYAuthOperationResultSuccess"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1success\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult\/title","value":"SYAuthOperationResult"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1unrecognizedResponseCode\/title","value":"SYAuthOperationResultUnrecognizedResponseCode"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1unrecognizedResponseCode\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultUnrecognizedResponseCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}