{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Receives notifications about authentication changes which are not explicitly requested by user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthDelegate"}],"title":"SYAuthDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SygicAuth@objc(pl)SYAuthDelegate","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate\/didChangeState(_:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate\/didSignOutWithoutRequest()"]}],"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthDelegate":{"role":"symbol","title":"SYAuthDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthDelegate"}],"abstract":[{"type":"text","text":"Receives notifications about authentication changes which are not explicitly requested by user."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthDelegate"}],"url":"\/documentation\/sygicauth\/syauthdelegate"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthDelegate/didChangeState(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didChangeState:"}],"role":"symbol","title":"didChangeState(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SYAuthState","preciseIdentifier":"c:@M@SygicAuth@E@SYAuthState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called every time authentication state is changed, regardless the reason of the change."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate\/didChangeState(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sygicauth\/syauthdelegate\/didchangestate(_:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthDelegate/didSignOutWithoutRequest()":{"navigatorTitle":[{"kind":"identifier","text":"didSignOutWithoutRequest"}],"role":"symbol","title":"didSignOutWithoutRequest()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSignOutWithoutRequest"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Means authentication was connected to an account (of any type), and became not connected to an account anymore."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate\/didSignOutWithoutRequest()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sygicauth\/syauthdelegate\/didsignoutwithoutrequest()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SYAuthDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate\/didChangeState(_:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate\/didSignOutWithoutRequest()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate\/title","value":"SYAuthDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate\/fragments","value":[{"kind":"identifier","text":"SYAuthDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate~1didChangeState(_:)\/title","value":"didChangeState:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate~1didChangeState(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didChangeState:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate~1didSignOutWithoutRequest()\/title","value":"didSignOutWithoutRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate~1didSignOutWithoutRequest()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSignOutWithoutRequest"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}