{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuth"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Sygic online services require HTTP requests to contain authentication headers provided by "},{"type":"codeVoice","code":"buildHeaders"},{"type":"text","text":" method,"},{"type":"text","text":" "},{"type":"text","text":"which is designed to be called for each request to Sygic online services."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Current authentication state can be managed by methods "},{"type":"codeVoice","code":"signIn"},{"type":"text","text":" and "},{"type":"codeVoice","code":"signOut"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To communicate with Sygic authentication server, "},{"type":"codeVoice","code":"SYAuth"},{"type":"text","text":" relies on "},{"type":"codeVoice","code":"SYAuthNetworkProvider"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To save and restore state after application restart, "},{"type":"codeVoice","code":"SYAuth"},{"type":"text","text":" relies on "},{"type":"codeVoice","code":"SYAuthStorageProvider"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauth"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sygic.SygicAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sygic.SygicAuth\/objc(pl)NSObject","doc:\/\/com.sygic.SygicAuth\/s7CVarArgP","doc:\/\/com.sygic.SygicAuth\/s28CustomDebugStringConvertibleP","doc:\/\/com.sygic.SygicAuth\/s23CustomStringConvertibleP","doc:\/\/com.sygic.SygicAuth\/SQ","doc:\/\/com.sygic.SygicAuth\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides authentication for Sygic online services."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuth"}],"title":"SYAuth","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SygicAuth@objc(cs)SYAuth","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuth"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/init(config:network:storage:queue:delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/delegate","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/state"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/buildHeaders(completion:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/notifyAuthenticationRejected()","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/requestAuthenticationRefresh()","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/signIn(withIdentity:completion:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/signOut(completion:)"]}],"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth":{"role":"symbol","title":"SYAuth","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuth"}],"abstract":[{"type":"text","text":"Provides authentication for Sygic online services."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuth"}],"url":"\/documentation\/sygicauth\/syauth"},"doc://com.sygic.SygicAuth/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sygic.SygicAuth\/objc(cs)NSObject"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/notifyAuthenticationRejected()":{"role":"symbol","title":"notifyAuthenticationRejected()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyAuthenticationRejected"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Lets SygicAuth know, that one of Sygic services has rejected the authentication of the current user identity."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/notifyAuthenticationRejected()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifyAuthenticationRejected"}],"url":"\/documentation\/sygicauth\/syauth\/notifyauthenticationrejected()"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/buildHeaders(completion:)":{"role":"symbol","title":"buildHeaders(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHeaders"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthBuildHeadersCompletion","preciseIdentifier":"s:9SygicAuth28SYAuthBuildHeadersCompletiona"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Prepares authentication headers based on the currently authenticated user identity."},{"type":"text","text":" "},{"type":"text","text":"Authentication headers are to be added to every NSURLRequest sent to Sygic online services."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/buildHeaders(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHeadersWithCompletion:"}],"url":"\/documentation\/sygicauth\/syauth\/buildheaders(completion:)"},"doc://com.sygic.SygicAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sygic.SygicAuth\/SH"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/requestAuthenticationRefresh()":{"role":"symbol","title":"requestAuthenticationRefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAuthenticationRefresh"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Refresh the access token for the currently authenticated user identity."},{"type":"text","text":" "},{"type":"text","text":"This could be necessary for some online services to apply license changes (e.g. after purchase of some features)."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/requestAuthenticationRefresh()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestAuthenticationRefresh"}],"url":"\/documentation\/sygicauth\/syauth\/requestauthenticationrefresh()"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthDelegate","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Delegate is notified about authentication changes which are not explicitly requested by user."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/sygicauth\/syauth\/delegate"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/signOut(completion:)":{"role":"symbol","title":"signOut(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signOut"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Stops using the currently authenticated user identity and"},{"type":"text","text":" "},{"type":"text","text":"removes authentication data from persistent storage (SYAuthStorageProvider)."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/signOut(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signOutWithCompletion:"}],"url":"\/documentation\/sygicauth\/syauth\/signout(completion:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/state":{"role":"symbol","title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthState","preciseIdentifier":"c:@M@SygicAuth@E@SYAuthState"}],"abstract":[{"type":"text","text":"Current authentication state. See SYAuthState for more details."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/state","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"state"}],"url":"\/documentation\/sygicauth\/syauth\/state"},"doc://com.sygic.SygicAuth/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sygic.SygicAuth\/s28CustomDebugStringConvertibleP"},"doc://com.sygic.SygicAuth/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sygic.SygicAuth\/s7CVarArgP"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/init(config:network:storage:queue:delegate:)":{"role":"symbol","title":"init(config:network:storage:queue:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthConfig","preciseIdentifier":"c:@M@SygicAuth@objc(cs)SYAuthConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"network"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthNetworkProvider","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthNetworkProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"storage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthStorageProvider","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthStorageProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthDelegate","preciseIdentifier":"c:@M@SygicAuth@objc(pl)SYAuthDelegate"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/init(config:network:storage:queue:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfig:network:storage:queue:delegate:"}],"url":"\/documentation\/sygicauth\/syauth\/init(config:network:storage:queue:delegate:)"},"doc://com.sygic.SygicAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sygic.SygicAuth\/SQ"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth/signIn(withIdentity:completion:)":{"role":"symbol","title":"signIn(withIdentity:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signIn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthIdentity","preciseIdentifier":"c:@M@SygicAuth@objc(cs)SYAuthIdentity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthSignInCompletion","preciseIdentifier":"s:9SygicAuth22SYAuthSignInCompletiona"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Authenticates with the user identity represented by SYAuthIdentity."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/signIn(withIdentity:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signInWithIdentity:completion:"}],"url":"\/documentation\/sygicauth\/syauth\/signin(withidentity:completion:)"},"doc://com.sygic.SygicAuth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sygic.SygicAuth\/s23CustomStringConvertibleP"},"doc://com.sygic.SygicAuth/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sygic.SygicAuth\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SYAuth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuth"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SYAuth"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/delegate","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/state"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/buildHeaders(completion:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/init(config:network:storage:queue:delegate:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/notifyAuthenticationRejected()","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/requestAuthenticationRefresh()","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/signIn(withIdentity:completion:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth\/signOut(completion:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuth"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/title","value":"SYAuth"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/fragments","value":[{"kind":"identifier","text":"SYAuth"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1notifyAuthenticationRejected()\/title","value":"notifyAuthenticationRejected"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1notifyAuthenticationRejected()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"notifyAuthenticationRejected"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1buildHeaders(completion:)\/title","value":"buildHeadersWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1buildHeaders(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"buildHeadersWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1requestAuthenticationRefresh()\/title","value":"requestAuthenticationRefresh"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1requestAuthenticationRefresh()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestAuthenticationRefresh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1signOut(completion:)\/title","value":"signOutWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1signOut(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signOutWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1state\/title","value":"state"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1state\/fragments","value":[{"kind":"identifier","text":"state"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1init(config:network:storage:queue:delegate:)\/title","value":"initWithConfig:network:storage:queue:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1init(config:network:storage:queue:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfig:network:storage:queue:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1signIn(withIdentity:completion:)\/title","value":"signInWithIdentity:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth~1signIn(withIdentity:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signInWithIdentity:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}