{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthStorageProvider"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each StorageProvider instance must be dedicated to only one SYAuth instance."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"SYAuth already manages synchronization during reading\/writing to the storage."},{"type":"text","text":" "},{"type":"text","text":"If used only by SYAuth, the storage doesn’t have to guarantee thread-safety."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthstorageprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthstorageprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides persistent storage of String values accessed by String keys."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthStorageProvider"}],"title":"SYAuthStorageProvider","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SygicAuth@objc(pl)SYAuthStorageProvider","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthStorageProvider"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider\/setString(_:forKey:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider\/string(forKey:)"]}],"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthStorageProvider/setString(_:forKey:)":{"navigatorTitle":[{"kind":"identifier","text":"setString:forKey:"}],"role":"symbol","title":"setString(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Writes a String value associated with a String key."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider\/setString(_:forKey:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sygicauth\/syauthstorageprovider\/setstring(_:forkey:)"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthStorageProvider":{"role":"symbol","title":"SYAuthStorageProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthStorageProvider"}],"abstract":[{"type":"text","text":"Provides persistent storage of String values accessed by String keys."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthStorageProvider"}],"url":"\/documentation\/sygicauth\/syauthstorageprovider"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthStorageProvider/string(forKey:)":{"navigatorTitle":[{"kind":"identifier","text":"stringForKey:"}],"role":"symbol","title":"string(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Reads a String value associated with a String key."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider\/string(forKey:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sygicauth\/syauthstorageprovider\/string(forkey:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthStorageProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthStorageProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SYAuthStorageProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider\/setString(_:forKey:)","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider\/string(forKey:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthStorageProvider"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthStorageProvider~1setString(_:forKey:)\/title","value":"setString:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthStorageProvider~1setString(_:forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setString:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthStorageProvider\/title","value":"SYAuthStorageProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthStorageProvider\/fragments","value":[{"kind":"identifier","text":"SYAuthStorageProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthStorageProvider~1string(forKey:)\/title","value":"stringForKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthStorageProvider~1string(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stringForKey:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}