{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthSendRequestCompletion","preciseIdentifier":"s:9SygicAuth27SYAuthSendRequestCompletiona","text":"SYAuthSendRequestCompletion"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthnetworkprovider\/sendrequest(_:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthnetworkprovider\/sendrequest(_:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider\/sendRequest(_:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sends the request and calls the completion asynchronously."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"sendRequest:completion:"}],"role":"symbol","title":"sendRequest(_:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthSendRequestCompletion","preciseIdentifier":"s:9SygicAuth27SYAuthSendRequestCompletiona"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SygicAuth@objc(pl)SYAuthNetworkProvider(im)sendRequest:completion:","required":true,"modules":[{"name":"SygicAuth"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthSendRequestCompletion":{"role":"symbol","title":"SYAuthSendRequestCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthSendRequestCompletion"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthSendRequestCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthSendRequestCompletion"}],"url":"\/documentation\/sygicauth\/syauthsendrequestcompletion"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthNetworkProvider":{"role":"symbol","title":"SYAuthNetworkProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthNetworkProvider"}],"abstract":[{"type":"text","text":"Provides network transport by asynchronous sending network requests."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthNetworkProvider"}],"url":"\/documentation\/sygicauth\/syauthnetworkprovider"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthNetworkProvider/sendRequest(_:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"sendRequest:completion:"}],"role":"symbol","title":"sendRequest(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SYAuthSendRequestCompletion","preciseIdentifier":"s:9SygicAuth27SYAuthSendRequestCompletiona"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sends the request and calls the completion asynchronously."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider\/sendRequest(_:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sygicauth\/syauthnetworkprovider\/sendrequest(_:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendRequest:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendRequest:completion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendRequest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLRequest","preciseIdentifier":"c:objc(cs)NSURLRequest"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"request"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSData *, NSURLResponse *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSData#*$objc(cs)NSURLResponse#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider\/title","value":"SYAuthNetworkProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider\/fragments","value":[{"kind":"identifier","text":"SYAuthNetworkProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider~1sendRequest(_:completion:)\/title","value":"sendRequest:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider~1sendRequest(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendRequest:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}