{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"badResponseData"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthoperationresult\/badresponsedata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthoperationresult\/badresponsedata"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/badResponseData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Response data cannot be parsed as JSON or JSON doesn’t contain all the required fields."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"badResponseData"}],"title":"SYAuthOperationResult.badResponseData","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SygicAuth@E@SYAuthOperationResult@SYAuthOperationResultBadResponseData","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultBadResponseData"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult":{"role":"symbol","title":"SYAuthOperationResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthOperationResult"}],"abstract":[{"type":"text","text":"Result of an authentication operation: signIn or buildHeaders."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResult"}],"url":"\/documentation\/sygicauth\/syauthoperationresult"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/badResponseData":{"role":"symbol","title":"SYAuthOperationResult.badResponseData","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"badResponseData"}],"abstract":[{"type":"text","text":"Response data cannot be parsed as JSON or JSON doesn’t contain all the required fields."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/badResponseData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultBadResponseData"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/badresponsedata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthOperationResultBadResponseData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultBadResponseData"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SYAuthOperationResultBadResponseData"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult\/title","value":"SYAuthOperationResult"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1badResponseData\/title","value":"SYAuthOperationResultBadResponseData"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1badResponseData\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultBadResponseData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}