{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inconsistentResponse"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthoperationresult\/inconsistentresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthoperationresult\/inconsistentresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/inconsistentResponse","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Network response is inconsistent, result is success but statusCode or data is nil."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inconsistentResponse"}],"title":"SYAuthOperationResult.inconsistentResponse","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SygicAuth@E@SYAuthOperationResult@SYAuthOperationResultInconsistentResponse","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultInconsistentResponse"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult":{"role":"symbol","title":"SYAuthOperationResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthOperationResult"}],"abstract":[{"type":"text","text":"Result of an authentication operation: signIn or buildHeaders."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResult"}],"url":"\/documentation\/sygicauth\/syauthoperationresult"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/inconsistentResponse":{"role":"symbol","title":"SYAuthOperationResult.inconsistentResponse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inconsistentResponse"}],"abstract":[{"type":"text","text":"Network response is inconsistent, result is success but statusCode or data is nil."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/inconsistentResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultInconsistentResponse"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/inconsistentresponse"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthOperationResultInconsistentResponse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultInconsistentResponse"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SYAuthOperationResultInconsistentResponse"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult\/title","value":"SYAuthOperationResult"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1inconsistentResponse\/title","value":"SYAuthOperationResultInconsistentResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1inconsistentResponse\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultInconsistentResponse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}