{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrongCredentials"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthoperationresult\/wrongcredentials"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthoperationresult\/wrongcredentials"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/wrongCredentials","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"User name or password is incorrect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrongCredentials"}],"title":"SYAuthOperationResult.wrongCredentials","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SygicAuth@E@SYAuthOperationResult@SYAuthOperationResultWrongCredentials","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultWrongCredentials"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult/wrongCredentials":{"role":"symbol","title":"SYAuthOperationResult.wrongCredentials","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrongCredentials"}],"abstract":[{"type":"text","text":"User name or password is incorrect."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult\/wrongCredentials","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResultWrongCredentials"}],"url":"\/documentation\/sygicauth\/syauthoperationresult\/wrongcredentials"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult":{"role":"symbol","title":"SYAuthOperationResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthOperationResult"}],"abstract":[{"type":"text","text":"Result of an authentication operation: signIn or buildHeaders."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResult"}],"url":"\/documentation\/sygicauth\/syauthoperationresult"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthOperationResultWrongCredentials"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultWrongCredentials"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SYAuthOperationResultWrongCredentials"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1wrongCredentials\/title","value":"SYAuthOperationResultWrongCredentials"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult~1wrongCredentials\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResultWrongCredentials"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult\/title","value":"SYAuthOperationResult"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}