{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"signedOut"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthstate\/signedout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthstate\/signedout"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/signedOut","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authentication is not connected to an account, user identity is represented by SYAuthConfig.deviceCode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"signedOut"}],"title":"SYAuthState.signedOut","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SygicAuth@E@SYAuthState@SYAuthStateSignedOut","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthStateSignedOut"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState":{"role":"symbol","title":"SYAuthState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthState"}],"abstract":[{"type":"text","text":"Authentication state."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthState"}],"url":"\/documentation\/sygicauth\/syauthstate"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState/signedOut":{"role":"symbol","title":"SYAuthState.signedOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"signedOut"}],"abstract":[{"type":"text","text":"Authentication is not connected to an account, user identity is represented by SYAuthConfig.deviceCode."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/signedOut","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthStateSignedOut"}],"url":"\/documentation\/sygicauth\/syauthstate\/signedout"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthStateSignedOut"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthStateSignedOut"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SYAuthStateSignedOut"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState\/title","value":"SYAuthState"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState\/fragments","value":[{"kind":"identifier","text":"SYAuthState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState~1signedOut\/title","value":"SYAuthStateSignedOut"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState~1signedOut\/fragments","value":[{"kind":"identifier","text":"SYAuthStateSignedOut"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}