{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"signedIn"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthstate\/signedin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthstate\/signedin"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/signedIn","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authentication is connected to an account (Sygic, Google, Facebook, Apple, or other)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"signedIn"}],"title":"SYAuthState.signedIn","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SygicAuth@E@SYAuthState@SYAuthStateSignedIn","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"SYAuthStateSignedIn"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState/signedIn":{"role":"symbol","title":"SYAuthState.signedIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"signedIn"}],"abstract":[{"type":"text","text":"Authentication is connected to an account (Sygic, Google, Facebook, Apple, or other)."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState\/signedIn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthStateSignedIn"}],"url":"\/documentation\/sygicauth\/syauthstate\/signedin"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState":{"role":"symbol","title":"SYAuthState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthState"}],"abstract":[{"type":"text","text":"Authentication state."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthState"}],"url":"\/documentation\/sygicauth\/syauthstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SYAuthStateSignedIn"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SYAuthStateSignedIn"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SYAuthStateSignedIn"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState~1signedIn\/title","value":"SYAuthStateSignedIn"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState~1signedIn\/fragments","value":[{"kind":"identifier","text":"SYAuthStateSignedIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState\/title","value":"SYAuthState"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState\/fragments","value":[{"kind":"identifier","text":"SYAuthState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}