{"variants":[{"paths":["\/documentation\/sygicauth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity"]},{"title":"Protocols","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthBuildHeadersCompletion","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthSendRequestCompletion","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthSignInCompletion"]},{"title":"Enumerations","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SygicAuth","title":"SygicAuth","symbolKind":"module","role":"collection","modules":[{"name":"SygicAuth"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth/SygicAuthVersionNumber":{"role":"symbol","title":"SygicAuthVersionNumber","fragments":[{"kind":"identifier","text":"SygicAuthVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for SygicAuth."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SygicAuthVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth\/sygicauthversionnumber"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SygicAuthVersionString":{"role":"symbol","title":"SygicAuthVersionString","fragments":[{"kind":"identifier","text":"SygicAuthVersionString"}],"abstract":[{"type":"text","text":"Project version string for SygicAuth."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SygicAuthVersionString","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth\/sygicauthversionstring"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthSendRequestCompletion":{"role":"symbol","title":"SYAuthSendRequestCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthSendRequestCompletion"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthSendRequestCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthSendRequestCompletion"}],"url":"\/documentation\/sygicauth\/syauthsendrequestcompletion"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthState":{"role":"symbol","title":"SYAuthState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthState"}],"abstract":[{"type":"text","text":"Authentication state."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthState"}],"url":"\/documentation\/sygicauth\/syauthstate"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthDelegate":{"role":"symbol","title":"SYAuthDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthDelegate"}],"abstract":[{"type":"text","text":"Receives notifications about authentication changes which are not explicitly requested by user."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthDelegate"}],"url":"\/documentation\/sygicauth\/syauthdelegate"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthNetworkProvider":{"role":"symbol","title":"SYAuthNetworkProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthNetworkProvider"}],"abstract":[{"type":"text","text":"Provides network transport by asynchronous sending network requests."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthNetworkProvider"}],"url":"\/documentation\/sygicauth\/syauthnetworkprovider"},"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthIdentity":{"role":"symbol","title":"SYAuthIdentity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthIdentity"}],"abstract":[{"type":"text","text":"User authentication identity (account)."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthIdentity"}],"url":"\/documentation\/sygicauth\/syauthidentity"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuth":{"role":"symbol","title":"SYAuth","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuth"}],"abstract":[{"type":"text","text":"Provides authentication for Sygic online services."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuth"}],"url":"\/documentation\/sygicauth\/syauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthBuildHeadersCompletion":{"role":"symbol","title":"SYAuthBuildHeadersCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthBuildHeadersCompletion"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthBuildHeadersCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthBuildHeadersCompletion"}],"url":"\/documentation\/sygicauth\/syauthbuildheaderscompletion"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthOperationResult":{"role":"symbol","title":"SYAuthOperationResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthOperationResult"}],"abstract":[{"type":"text","text":"Result of an authentication operation: signIn or buildHeaders."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthOperationResult"}],"url":"\/documentation\/sygicauth\/syauthoperationresult"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthSignInCompletion":{"role":"symbol","title":"SYAuthSignInCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthSignInCompletion"}],"abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthSignInCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthSignInCompletion"}],"url":"\/documentation\/sygicauth\/syauthsignincompletion"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig":{"role":"symbol","title":"SYAuthConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthConfig"}],"abstract":[{"type":"text","text":"Authentication parameters which are user-independent, and remain constant for an application installed on a specific device."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthConfig"}],"url":"\/documentation\/sygicauth\/syauthconfig"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthStorageProvider":{"role":"symbol","title":"SYAuthStorageProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthStorageProvider"}],"abstract":[{"type":"text","text":"Provides persistent storage of String values accessed by String keys."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthStorageProvider"}],"url":"\/documentation\/sygicauth\/syauthstorageprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthIdentity"]},{"title":"Protocols","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthDelegate","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthNetworkProvider","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthStorageProvider"]},{"title":"Variables","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SygicAuthVersionNumber","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SygicAuthVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthOperationResult","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthState"]}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState\/title","value":"SYAuthState"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthState\/fragments","value":[{"kind":"identifier","text":"SYAuthState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate\/title","value":"SYAuthDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthDelegate\/fragments","value":[{"kind":"identifier","text":"SYAuthDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider\/title","value":"SYAuthNetworkProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthNetworkProvider\/fragments","value":[{"kind":"identifier","text":"SYAuthNetworkProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity\/title","value":"SYAuthIdentity"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthIdentity\/fragments","value":[{"kind":"identifier","text":"SYAuthIdentity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/title","value":"SYAuth"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuth\/fragments","value":[{"kind":"identifier","text":"SYAuth"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult\/title","value":"SYAuthOperationResult"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthOperationResult\/fragments","value":[{"kind":"identifier","text":"SYAuthOperationResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig\/title","value":"SYAuthConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig\/fragments","value":[{"kind":"identifier","text":"SYAuthConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthStorageProvider\/title","value":"SYAuthStorageProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthStorageProvider\/fragments","value":[{"kind":"identifier","text":"SYAuthStorageProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}