{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sygicauth\/syauthconfig\/clientsecret"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sygicauth\/syauthconfig\/clientsecret"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/clientSecret","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Client Secret specified during initialization."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"clientSecret","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SygicAuth@objc(cs)SYAuthConfig(py)clientSecret","modules":[{"name":"SygicAuth"}],"navigatorTitle":[{"kind":"identifier","text":"clientSecret"}]},"hierarchy":{"paths":[["doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig"]]},"references":{"doc://com.sygic.SygicAuth/documentation/SygicAuth":{"role":"collection","title":"SygicAuth","abstract":[],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth","kind":"symbol","type":"topic","url":"\/documentation\/sygicauth"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig/clientSecret":{"role":"symbol","title":"clientSecret","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Client Secret specified during initialization."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig\/clientSecret","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientSecret"}],"url":"\/documentation\/sygicauth\/syauthconfig\/clientsecret"},"doc://com.sygic.SygicAuth/documentation/SygicAuth/SYAuthConfig":{"role":"symbol","title":"SYAuthConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYAuthConfig"}],"abstract":[{"type":"text","text":"Authentication parameters which are user-independent, and remain constant for an application installed on a specific device."}],"identifier":"doc:\/\/com.sygic.SygicAuth\/documentation\/SygicAuth\/SYAuthConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYAuthConfig"}],"url":"\/documentation\/sygicauth\/syauthconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"clientSecret"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clientSecret"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *"},{"kind":"identifier","text":"clientSecret"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1clientSecret\/title","value":"clientSecret"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig~1clientSecret\/fragments","value":[{"kind":"identifier","text":"clientSecret"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig\/title","value":"SYAuthConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.sygic.SygicAuth~1documentation~1SygicAuth~1SYAuthConfig\/fragments","value":[{"kind":"identifier","text":"SYAuthConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}